name: 🤘Deploy
on: 
  push:
    branches:
      - main
jobs:
  config:
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or another version you prefer

    - name: 🤖 Install dependencies
      run: npm install

    - name: Replace DB credentials in wp-config.php
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_HOST: ${{ secrets.DB_HOST }}
      run: node builders/processwire-db.js

    - name: Upload config.php as artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: my_file.php
        retention-days: 1

    # Further steps if needed, like deploying to a server.
  deploy:
    name: 🎉 Deploy
    needs: config
    runs-on: ubuntu-latest
    steps: 
    - name: 🚚 Get latest code
      uses: actions/checkout@v3   
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        name: config
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.gitdemo.sfadev.com
        username: git@gitdemo.sfadev.com
        password: ${{ secrets.ftp_password }}
