name: 🔒 Update Credentials

on: 
  push:
    branches:
      - main

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # or another version you prefer

    - name: Install dependencies
      run: npm install

    - name: Replace DB credentials in wp-config.php
      env:
        DB_NAME: ${{ env.DB_NAME }}
        DB_USER: ${{ env.DB_USER }}
        DB_PASSWORD: ${{ env.DB_PASS }}
        DB_HOST: ${{ env.DB_HOST }}
      run: node builders/processwire-db.js


    # Further steps if needed, like deploying to a server.
